import { isWithinBusinessHours } from './whatsapp-rules';

export type QueueMessage = {
  id: string;
  contactId: string;
  opportunityId: string;
  templateName: string;
  variables: string[];
  status: 'pending' | 'approved' | 'sent' | 'failed' | 'queued_for_hours';
  proposedText: string; // The text generated by AI for review
  createdAt: Date;
  updatedAt: Date;
};

// In a real app, this would be a database table (e.g. SQLite or Postgres)
// For MVP, we'll simulate an in-memory or basic file-based queue if needed,
// but let's mock the interface.
let messageQueue: QueueMessage[] = [];

export async function addMessageToQueue(message: Omit<QueueMessage, 'id' | 'status' | 'createdAt' | 'updatedAt'>) {
  const newMessage: QueueMessage = {
    ...message,
    id: `msg_${Math.random().toString(36).substr(2, 9)}`,
    status: 'pending', // Requires human approval
    createdAt: new Date(),
    updatedAt: new Date()
  };
  messageQueue.push(newMessage);
  return newMessage;
}

export async function getPendingMessages() {
  return messageQueue.filter(m => m.status === 'pending');
}

export async function approveMessage(id: string) {
  const msg = messageQueue.find(m => m.id === id);
  if (!msg) throw new Error('Message not found');

  msg.status = 'approved';
  msg.updatedAt = new Date();
  
  // Try to process immediately
  await processQueue();
  
  return msg;
}

export async function processQueue() {
  const approvedMessages = messageQueue.filter(m => m.status === 'approved' || m.status === 'queued_for_hours');
  
  if (approvedMessages.length === 0) return;

  const canSendNow = isWithinBusinessHours();

  for (const msg of approvedMessages) {
    if (!canSendNow) {
      msg.status = 'queued_for_hours';
      msg.updatedAt = new Date();
      console.log(`[Queue] Message ${msg.id} queued (outside business hours)`);
      continue;
    }

    try {
      // Simulate API Call to GHL MCP or Direct API
      console.log(`[WhatsApp API] Sending Template '${msg.templateName}' to Contact '${msg.contactId}'`);
      // await sendGHLWhatsAppTemplate(msg.contactId, msg.templateName, msg.variables);
      
      msg.status = 'sent';
      msg.updatedAt = new Date();
    } catch (error) {
      console.error(`[Queue] Failed to send message ${msg.id}`, error);
      msg.status = 'failed';
      msg.updatedAt = new Date();
    }
  }
}
